apiVersion: v1
kind: configMap
metadata:
  name: configmap-app
data:
  NODE_ENV: "production"
  PORT: "3000"
  MONGO_URI: "mongodb://hrapp:hrapp123@mongodb-service:27017/hr_system?authSource=hr_system"
  DB_NAME: "hr_system"
  MONGO_USERNAME: "hrapp"
  MONGO_PASSWORD: "hrapp123"
  DEFAULT_ADMIN_ID: "admin"
  DEFAULT_ADMIN_PASSWORD: "admin123"
  LOG_LEVEL: "info"


  